Fix typescript error TS2774
Error:
- This condition will always return true since this function is always defined. Did you mean to call it instead?

Fix:
- [EuiPinnableListGroup] Remove unnecessary check, pinnable serves that purpose
- [EuiOverlayMask] Remove unnecessary check, there's already an early return at the beginning of the block
- [extra] DRY out portalTarget var - it's being used interchangably with overlayMaskNode.current